os: linux
dist: bionic
language: python
cache: pip

python: 
  - 3.8
  - 3.9

install:
  - pip install -U pip
  - pip install -U dateutils
  - pip install -r requirements.txt

script:
  - python -m pytest tests/
