os: linux
dist: bionic
language: python
cache: pip

python:
  - 3.8
  - 3.9

install:
  - pip install -U pip
  - pip install --user pipx
  - pipx install poetry
  - poetry install

script:
  - poetry run pytest
